export const colors = {
  primary: '#FF3D43',
  primaryPressed: '#E52F35',
  primarySoft: '#FFF0F1',
  primaryBorder: '#FFD5D7',
  background: '#F8F9FC',
  surface: '#FFFFFF',
  surfaceMuted: '#F4F5F8',
  overlay: 'rgba(17, 24, 39, 0.45)',
  textPrimary: '#111827',
  textSecondary: '#6B7280',
  textMuted: '#9CA3AF',
  textInverse: '#FFFFFF',
  border: '#E7E9EE',
  borderStrong: '#D1D5DB',
  divider: '#EEF0F3',
  success: '#16A34A',
  successSoft: '#ECFDF3',
  warning: '#D97706',
  warningSoft: '#FFF7E6',
  info: '#2563EB',
  infoSoft: '#EFF6FF',
  danger: '#DC2626',
  dangerSoft: '#FEF2F2',
  purple: '#7C3AED',
  purpleSoft: '#F5F3FF',
  rating: '#F59E0B',
  disabled: '#D1D5DB',
  disabledBackground: '#F3F4F6',
  transparent: 'transparent',
} as const;

export type ColorToken = keyof typeof colors;
